### ISSUE TITLE
Looks like the package on npm needs a bluebird dependency

### ISSUE THREAD

**Issue by kstaken** [godber/teraslice-top#14]
```
module.js:327
    throw err;
    ^

Error: Cannot find module 'bluebird'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/teraslice-top/index.js:5:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

**Comment by godber** [comment]
I think we're past this issue: 

https://github.com/godber/teraslice-top/blob/master/package.json#L28
